service:
  name: root-config-service
  host: 39.103.176.179
  port: 8010
  tags: ['web']
consul:
  address: consul.dev.xbt-dev.top
  host: 39.103.176.179
  port: 10008
  check:
    protocol: http
    route: /health
    interval: 30s
    timeout: 3s
    maxRetry: 5
    retryInterval: 5s
    deregisterCriticalServiceAfter: 60m
